"""Code-interpreter tools exposed to the LLM via the Teams AI SDK.

The single, ChatGPT-style primitive is ``run_python``: the model writes Python to
analyse uploaded files, compute results, build charts and *generate* documents
(.xlsx/.docx/.pptx/.pdf/.png/.zip). Files the code writes are captured, stored
behind expiring download links, and delivered to the user by the caller after the
LLM turn completes.

Usage:
    turn = InterpreterTurn(input_files={"data.xlsx": raw_bytes})
    tools = build_interpreter_tools(turn)
    chat_prompt = ChatPrompt(model, functions=tools)
    await chat_prompt.send(...)
    # after send(): deliver turn.artifacts to the user
"""

from __future__ import annotations

import asyncio
import logging
import os
from dataclasses import dataclass, field
from typing import Optional

from pydantic import BaseModel, Field

from interpreter.sandbox import run_python
from generation.file_store import download_url, get_artifact_store

logger = logging.getLogger(__name__)

# Hard ceiling on how many code executions one user turn may trigger, to bound
# latency/cost even if the model loops.
MAX_RUNS_PER_TURN = int(os.environ.get("INTERPRETER_MAX_RUNS_PER_TURN", "6"))
SANDBOX_TIMEOUT = float(os.environ.get("INTERPRETER_TIMEOUT_SECONDS", "30"))
SANDBOX_MEMORY_MB = int(os.environ.get("INTERPRETER_MEMORY_MB", "768"))


@dataclass
class Artifact:
    """A file produced during the turn, ready to deliver to the user."""

    filename: str
    token: str
    size: int
    url: str


@dataclass
class InterpreterTurn:
    """Per-turn state shared with the tool handlers (built fresh each message)."""

    # Uploaded files available to the code, by filename -> raw bytes.
    input_files: dict[str, bytes] = field(default_factory=dict)
    # Files generated by the code, to be sent back to the user after the LLM turn.
    artifacts: list[Artifact] = field(default_factory=list)
    runs: int = 0

    def input_manifest(self) -> str:
        if not self.input_files:
            return "(none)"
        lines = []
        for name, data in self.input_files.items():
            lines.append(f"- {name} ({len(data):,} bytes)")
        return "\n".join(lines)


class RunPythonParams(BaseModel):
    """Parameters for the run_python tool."""

    code: str = Field(
        ...,
        description=(
            "Python 3 source to execute. Uploaded files are in the current "
            "directory under their original filename. Use print() for findings. "
            "Save any file you want to give the user (charts, .xlsx, .docx, "
            ".pptx, .pdf, .zip, .csv, .txt) into the current directory."
        ),
    )
    purpose: str = Field(
        default="",
        description="One short sentence describing what this code does (for logging).",
    )


def _format_result(turn: InterpreterTurn, res, new_artifacts: list[Artifact]) -> str:
    """Build the text observation returned to the model after an execution."""
    parts: list[str] = []
    if res.timed_out:
        parts.append(f"EXECUTION TIMED OUT after {SANDBOX_TIMEOUT:.0f}s. "
                     "Simplify the code or process less data.")
    elif res.error:
        parts.append("EXECUTION FAILED with an error:\n" + res.error.strip())
    else:
        parts.append("Execution succeeded.")

    if res.stdout.strip():
        parts.append("STDOUT:\n" + res.stdout.strip())
    if res.result_repr:
        parts.append("`result` = " + res.result_repr)
    if new_artifacts:
        names = ", ".join(a.filename for a in new_artifacts)
        parts.append(
            f"Generated file(s): {names}. These are being delivered to the user "
            "automatically — do NOT print download links yourself; just tell the "
            "user what each file contains."
        )
    elif not res.error and not res.timed_out:
        parts.append("No output files were created.")
    return "\n\n".join(parts)


def build_interpreter_tools(turn: InterpreterTurn) -> list:
    """Build the list of SDK Function tools bound to ``turn``."""
    # Imported here so this module stays importable even if the SDK is absent
    # (e.g. unit tests of the sandbox alone).
    from microsoft_teams.ai.function import Function

    store = get_artifact_store()

    async def _run_python_handler(params: RunPythonParams) -> str:
        if turn.runs >= MAX_RUNS_PER_TURN:
            return ("Run limit reached for this request. Summarize what you have "
                    "and stop calling run_python.")
        turn.runs += 1
        purpose = (params.purpose or "").strip()
        logger.info("🐍 run_python #%d | purpose=%s | code_chars=%d",
                    turn.runs, purpose[:80] or "(none)", len(params.code or ""))

        res = await asyncio.to_thread(
            run_python,
            params.code or "",
            input_files=turn.input_files,
            timeout=SANDBOX_TIMEOUT,
            memory_mb=SANDBOX_MEMORY_MB,
        )

        new_artifacts: list[Artifact] = []
        try:
            for fname, fpath in (res.files or {}).items():
                try:
                    size = os.path.getsize(fpath)
                    token = store.save_file(fpath, fname)
                    art = Artifact(filename=fname, token=token, size=size, url=download_url(token))
                    turn.artifacts.append(art)
                    new_artifacts.append(art)
                except Exception as exc:  # pragma: no cover
                    logger.warning("Failed to store artifact %s: %s", fname, exc)
        finally:
            res.cleanup()

        observation = _format_result(turn, res, new_artifacts)
        logger.info("🐍 run_python #%d done | ok=%s | files=%d | obs_chars=%d",
                    turn.runs, res.ok, len(new_artifacts), len(observation))
        return observation

    run_python_tool = Function[RunPythonParams](
        name="run_python",
        description=(
            "Run Python to analyze data, do calculations, create charts/visualizations, "
            "and GENERATE documents for the user. Use it for: spreadsheet math and "
            "manipulation (pandas/openpyxl), comparisons, statistics, plotting "
            "(matplotlib), and producing .xlsx, .docx, .pptx, .pdf, .csv, .txt, .png or "
            ".zip files. Available libraries include pandas, numpy, openpyxl, matplotlib, "
            "python-docx, python-pptx, reportlab, Pillow, pypdf. There is NO network "
            "access. Uploaded files in this conversation are in the current working "
            "directory:\n" + turn.input_manifest() +
            "\nSave any file you want to deliver to the user into the current directory."
        ),
        parameter_schema=RunPythonParams,
        handler=_run_python_handler,
    )

    return [run_python_tool]
